### ISSUE TITLE
browserstack results from Catalina/Safari 13.0.2 session

### ISSUE THREAD

**Issue by glassworm** [sudara/stitchES#66]
first- thank you @sudara, stitchES has been a huge help during efforts to better understand the quirks and limitations of HTML 5 audio.  I really appreciate the existence and periodic maintenance of this library.

In early 2019 I wrote some vue.js code inspired by earlier versions of this pkg and recently had the misfortune of testing that code in Safari, noticing weird behavior tying back to  ```oncanplaythrough``` not firing like it is in other browsers and generally breaking though same code is still solid in recent Chrome, FF, etc.

Above sent me back to the promise land of this repo to see what I needed to do, and reading the README, it compelled me to set up a browserstack account and run the ```yarn browserstack``` command (after first editing the conf file to only run against Catalina / Safari 13):

<img width="784" alt="Screen Shot 2020-03-20 at 10 07 38 AM" src="https://user-images.githubusercontent.com/43278397/77188092-b143c700-6a92-11ea-9325-829895620a19.png">

I can't yet unfortunately myself understand those errors but I am going to keep digging and see what I find.

Thanks in advance for any guidance others may have to get those tests to pass against Safari 13.  Once they do pass I plan to work on being re-inspired by this code to get my vue.js code working again in all major browsers.

**Comment by sudara** [comment]
Hey @glassworm! 

Wow, it's nice to hear this was useful for someone else already! It's still under active development with the end goal of it becoming a dependency for https://github.com/sudara/alonetone — note that it's not actively integrated there yet, in part because I've still been working my way through all of the browser/nightwatch/browserstack issues — it's been a ridiculous amount of work to try and get that testing stack stable.

The testing stack is still very fragile, so it's difficult to tell which failures are legit or not. Browserstack regularly has all kinds of connection errors that break builds, typically on macOS or iOS. Example, here's the nightly stitchES job running with no changes between builds:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/472/77189886-9431e700-6ad8-11ea-8ca9-028aa252d41d.png">

> misfortune of testing that code in Safari, noticing weird behavior tying back to `oncanplaythrough` not firing like it is in other browsers

Safari is definitely the worst offender when it comes to HTML5 audio, there are a few persistent quirks (after years of bugs being filed). Is the one you are referring to that `oncanplaythrough` won't fire until all of the audio file is downloaded? The other browsers will fire it when they feel confident playback will be uninterrupted

> it compelled me to set up a browserstack account and run the yarn browserstack

At least part of the issue here is that the Safari 13 webdriver is broken and can't click on things properly. That's [why StitchES doesn't currently test against it](https://github.com/sudara/stitchES/blob/master/nightwatch-browserstack.conf.js#L64). The root issue is filed (and apparently fixed in some upcoming release) here https://bugs.webkit.org/show_bug.cgi?id=202589

**Comment by glassworm** [comment]
@sudara yes, your package is providing a great service! 

I regret only just now noticing the specific Safari 13 comment in ```nightwatch-browserstack.conf.js``` which would have prevented me from distracting from the real issue, yes ```oncanplaythrough``` is suddenly misbehaving for me wherein the event doesn't fire (I think) until user clicks again, whereas other browsers fire that event as they always have.  My current plan is to again look at stitchES (just noticed ```improve_playback```) and try to find my issue by studying what is likely working fine in this repo.

Thanks again.

**Comment by sudara** [comment]
> until user clicks again

Interesting...  Let me know more reproduction detail if you still run into problems. Stitches is currently only using `oncanplaythrough` to decide if something is loaded: https://github.com/sudara/stitchES/blob/master/src/audio_node.js#L20

However, that logic is only being used to decide whether a loading indicator should be shown...

Related: I've been wanting to use a backend to serve the audio files specifically so we can test loading situations, range headers, etc. Everything in our tests currently loads instantly. I haven't yet put stitches in production, so it wouldn't surprise me if you ran into something we haven't built for yet...

**Comment by glassworm** [comment]
If I rediscover the Safari 13 bug I will post a separate issue, thank you for the info.
